"""Generate realistic synthetic AI image test samples with metadata."""
from __future__ import annotations

import io
import struct
import zlib
from pathlib import Path
from PIL import Image, PngImagePlugin


def create_sample_png_with_ai_metadata(output_path: Path) -> Path:
    """Create a PNG image embedded with Stable Diffusion prompts and ComfyUI workflow JSON."""
    img = Image.new("RGB", (128, 128), color=(73, 109, 137))
    
    pnginfo = PngImagePlugin.PngInfo()
    # 1. Stable Diffusion parameters
    pnginfo.add_text(
        "parameters",
        "cyberpunk street, neon lights, 8k resolution, cinematic lighting\n"
        "Negative prompt: low quality, blurry, deformed\n"
        "Steps: 28, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 123456789, Size: 512x512, Model: sd_xl_base_1.0"
    )
    # 2. ComfyUI workflow JSON graph
    pnginfo.add_text(
        "workflow",
        '{"nodes": [{"id": 1, "type": "KSampler", "class_type": "KSampler"}, {"id": 2, "type": "CLIPTextEncode"}]}'
    )
    # 3. Custom AI prompt tag
    pnginfo.add_text("prompt", '{"3": {"class_type": "KSampler", "inputs": {"seed": 987654321}}}')

    output_path.parent.mkdir(parents=True, exist_ok=True)
    img.save(output_path, "PNG", pnginfo=pnginfo)
    return output_path


def create_sample_jpeg_with_ai_metadata(output_path: Path) -> Path:
    """Create a JPEG image embedded with simulated APP1 (Exif/XMP), APP2 (ICC), APP11 (C2PA)."""
    img = Image.new("RGB", (128, 128), color=(200, 100, 50))
    raw_buf = io.BytesIO()
    img.save(raw_buf, format="JPEG", quality=90)
    data = raw_buf.getvalue()

    # Inject APP1 (XMP with C2PA claim) and APP11 (JUMBF C2PA box)
    soi = data[:2]
    rest = data[2:]

    # Simulated APP1 Exif with Midjourney comment
    exif_payload = b"Exif\x00\x00\x49\x49\x2A\x00" + b"Midjourney v6 prompt: futuristic city --ar 16:9 --v 6.0"
    app1_exif = b"\xFF\xE1" + struct.pack(">H", len(exif_payload) + 2) + exif_payload

    # Simulated APP1 XMP with C2PA manifest
    xmp_payload = (
        b"http://ns.adobe.com/xap/1.0/\x00"
        b"<x:xmpmeta xmlns:x='adobe:ns:meta/'>"
        b"<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#'>"
        b"<rdf:Description xmlns:c2pa='http://c2pa.org/manifest/' c2pa:claim='dall-e-3-synthetic'>"
        b"</rdf:Description></rdf:RDF></x:xmpmeta>"
    )
    app1_xmp = b"\xFF\xE1" + struct.pack(">H", len(xmp_payload) + 2) + xmp_payload

    # Simulated APP2 ICC Profile
    icc_payload = b"ICC_PROFILE\x00\x01\x01" + b"\x00" * 32
    app2_icc = b"\xFF\xE2" + struct.pack(">H", len(icc_payload) + 2) + icc_payload

    # Simulated APP11 JUMBF / C2PA Box
    c2pa_payload = b"JP\x00\x00jumbf\x00\x00c2pa.claim.synthetic.contentcredentials"
    app11_c2pa = b"\xFF\xEB" + struct.pack(">H", len(c2pa_payload) + 2) + c2pa_payload

    # Simulated APP13 IPTC
    iptc_payload = b"Photoshop 3.0\x008BIM\x04\x04\x00\x00\x00\x20trainedAlgorithmicMedia"
    app13_iptc = b"\xFF\xED" + struct.pack(">H", len(iptc_payload) + 2) + iptc_payload

    output_data = soi + app1_exif + app1_xmp + app2_icc + app11_c2pa + app13_iptc + rest
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(output_data)
    return output_path


def create_sample_webp_with_metadata(output_path: Path) -> Path:
    """Create a WebP image with EXIF and XMP metadata."""
    img = Image.new("RGB", (128, 128), color=(50, 150, 200))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    exif_data = b"Exif\x00\x00\x49\x49\x2A\x00Generated by Stable Diffusion WebUI"
    xmp_data = b"<x:xmpmeta>Synthetic AI Art</x:xmpmeta>"
    
    img.save(output_path, "WEBP", exif=exif_data, quality=90)
    return output_path


def generate_all_samples(target_dir: Path) -> dict[str, Path]:
    target_dir.mkdir(parents=True, exist_ok=True)
    png_path = create_sample_png_with_ai_metadata(target_dir / "sample_sd_comfyui.png")
    jpg_path = create_sample_jpeg_with_ai_metadata(target_dir / "sample_c2pa_midjourney.jpg")
    webp_path = create_sample_webp_with_metadata(target_dir / "sample_ai.webp")
    return {
        "png": png_path,
        "jpeg": jpg_path,
        "webp": webp_path,
    }


if __name__ == "__main__":
    samples = generate_all_samples(Path("scratch/samples"))
    print("Samples created successfully:")
    for k, p in samples.items():
        print(f" - [{k}]: {p} ({p.stat().st_size} bytes)")
